### ISSUE TITLE
Not able to view JMeter report

### ISSUE THREAD

**Issue by trg6669** [lakshaykaushik/PublishHTMLReport#15]
I am just trying to publish JMeter HTML report that I generate using pipeline.
JMeter command is:
call jmeter -J csvfile="$(System.DefaultWorkingDirectory)/_CCM.API.Test.Files/Test_Data_SQL_Queries/$(Feature).csv" -J users=$(Users) -J lifeT=$(LifeSpan) -n -t 
call jmeter -g "%rp%\results.csv" -o "%rp%\REPORT"

Report generates okay, I didn't see any errors while using extension either in logs but no report is seen anywhere. Where am I supposed to see this?

**Comment by lakshaykaushik** [comment]
You are supposed to use the task of the extension and provide the root folder of report as Jmeter path. Please go through the documentation
