### ISSUE TITLE
Publish HTML Report in Release Pipeline? 

### ISSUE THREAD

**Issue by dornfeder** [lakshaykaushik/PublishHTMLReport#16]
Hi, 

does your plugin also work in Release Pipelines or only in Build Pipelines? When i try to use the task to publish a generic HTML file within a release pipeline, the task itself runs successfully, but the pipeline doesn't show any tab related to HTML Reports. 

Am I doing something wrong or is this just not supported? 

Thanks

**Comment by TOMKT** [comment]
Same issue here... correct handling but no tab in release

**Comment by lakshaykaushik** [comment]
This works only in Build Pipelines, not release pipelines.
