### ISSUE TITLE
Does this task work with yml pipelines?

### ISSUE THREAD

**Issue by kiruthigavasu** [lakshaykaushik/PublishHTMLReport#18]
Hello Sir, thanks much for your wonderful extension and a much needed one. Just curious, when i try to add this using classic view, I am unable to add it to my pipelines. And looking at your usage documentation your example is for yaml . So does this extension work only for yaml and not classic? Thx much for your time.

**Comment by kshitijcode** [comment]
@kiruthigavasu The extension works with a classic view as well. 
You would need to install it from the marketplace and add it as a task in the stage. 

<img width="1457" alt="Screenshot 2020-12-16 at 4 46 33 PM" src="https://user-images.githubusercontent.com/15818044/102341760-52c65d80-3fbe-11eb-8f13-df8c5bf08258.png">

**Comment by lakshaykaushik** [comment]
This works with classic as well, as shown by kshitijcode in above screenshot. Closing this
