### ISSUE TITLE
TestNG Extent Report HTML is not rendering properly

### ISSUE THREAD

**Issue by sriramdasbalaji** [lakshaykaushik/PublishHTMLReport#20]
Hi Kaushik,

We have TestNG test reports generated by Extent Reports. We tried to publish the report using your extension. Unfortunately its not rendering properly. PFB images
Actual Report 
![image](https://user-images.githubusercontent.com/13716984/103620690-f1a8fe80-4f59-11eb-9922-46344994cd94.png)

Published report using extension
![image](https://user-images.githubusercontent.com/13716984/103620792-21f09d00-4f5a-11eb-8e95-4c2cdb528d9e.png)

Any suggestion to fix this issue would help us.

Thanks

**Comment by lakshaykaushik** [comment]
Hi as mentioned in the documentation, you will need to build functionality to support something like testng. This extension fully supports jmeter and simple one pager html reports
