### ISSUE TITLE
plugin not visible in Azure DevOps Server 2019

### ISSUE THREAD

**Issue by johnqa** [lakshaykaushik/PublishHTMLReport#21]
Hi, 

I installed the plugin in Azure DevOps Server 2019 (standalone installation) but I cannot see any task or extra tab related with the plugin in builds.

Is there anything I have to do after installing the extension?

Can this be used with classic (not yaml) builds?

Thank you,
Ioan

**Comment by lakshaykaushik** [comment]
Can you paste a screenshot where are you looking?

**Comment by esx-alexandergeorge** [comment]
I too am not able to see the "Publish HTML" area after my pipeline processes are completed. (Azure Devops Server 2019) Where is this supposed to be visible? It runs fine in my pipeline, but the report is no where to be found within ADO

**Comment by johnqa** [comment]
Hi,

I cannot see it anywhere. I see it is installed, but I don't find any related tasks in any project.

I am using classic builds (not yaml).

Maybe you can send me some screenshots with where the plugin is visible so I can look at.

Thanks,
John

**Comment by johnqa** [comment]
For me the problem was solved. I did not installed the plugin properly.

Now after installation it seems to work.

Thank you,
John

**Comment by esx-alexandergeorge** [comment]
> For me the problem was solved. I did not installed the plugin properly.
> 
> Now after installation it seems to work.
> 
> Thank you,
> John

Can you please share what you did originally and how you fixed it? I may be experiencing the same issue.

**Comment by johnqa** [comment]
Well I have added the extension to Local Extensions but did not installed it in my collection. 

As a result the task was not visible. Also when looking at the collection's extensions it was not there.

**Comment by esx-alexandergeorge** [comment]
> Well I have added the extension to Local Extensions but did not installed it in my collection.
> 
> As a result the task was not visible. Also when looking at the collection's extensions it was not there.

Ok I see, you were not able to see it to be able to add it. My issue is that it is added to a release pipeline as a task, but I have no clue as to where the report is visible after run. Is it working for you?

**Comment by lakshaykaushik** [comment]
Hi @esx-alexandergeorge , are you using release pipeline or build pipeline? Can you verify it in build pipeline too, if you are able to see the tab?

**Comment by esx-alexandergeorge** [comment]
Hello - it is in a Release pipeline.  Can we please have this updated to consider the type of pipeline? That would be extremely useful.

**Comment by lakshaykaushik** [comment]
Working on the release pipeline part.

**Comment by lakshaykaushik** [comment]
duplicate.  Tracking this in https://github.com/lakshaykaushik/PublishHTMLReport/issues/24
