### ISSUE TITLE
Opening Robot Framework log failed

### ISSUE THREAD

**Issue by vinodsunkara** [lakshaykaushik/PublishHTMLReport#23]
Hello Team

I have a file generated by the robot framework and wanted to publish this file by using the PublishHTMLReport task in our ADO pipeline. However, it is giving an error "Opening Robot Framework log failed". 

- Verify that you have JavaScript enabled in your browser.
- Make sure you are using a modern enough browser. If using Internet Explorer, version 8 or newer is required.
- Check are there messages in your browser's JavaScript error log. Please report the problem if you suspect you have encountered a bug.

**The Javascript has already been enabled in my browser. Can we use this task to publish this type of HTML files?**

![image](https://user-images.githubusercontent.com/37222937/105737405-840a4580-5efb-11eb-8411-a2de399c85f7.png)

Network trace:

![image](https://user-images.githubusercontent.com/37222937/105738787-08a99380-5efd-11eb-8ee9-5d3f67d26389.png)

**Comment by lakshaykaushik** [comment]
Hi Vinod, Robot test report will not work out of the box from the extension. It will need code change in the extension, i have documented how anyone can do code changes to the extension and support their tool of choice. I will also be happy to receive a PR which supports robot tests and merge it in this extension.
