### ISSUE TITLE
Report not visible in Release Pipeline (ADO Server 2019)

### ISSUE THREAD

**Issue by esx-alexandergeorge** [lakshaykaushik/PublishHTMLReport#24]
I have a JMeter stage in a release pipeline, where the SystemDefaultWorkingDirectory has the report files. It appears that no matter what options I input, or alternative syntax I use, the task always "appears" as it was successful in the pipeline, but there is no report to be found anywhere in my ADO. Pease assist. Thanks!

**Comment by Tyale-cpu** [comment]
HI - I have the exact same question - does this only work in a Build Pipeline and not a Release pipeline.  My task says it is successfull, but as Alexander has noted, where do you find the published report?

**Comment by arjuntamirikoch** [comment]
Hello I too do not see any Html Tab. My task shows it's successful. Can anyone help ?
I'm publishing generic Html and used the guidelines from you.

**Comment by mhoult22** [comment]
I also would really appreciate this feature as our JMeter tests are running in release pipeline only, not build pipeline.  Can I just confirm @lakshaykaushik , in this previous issue, you said that release pipeline is not supported (https://github.com/lakshaykaushik/PublishHTMLReport/issues/16).  Is the plan now to try and support release pipelines?  Thank you.

**Comment by lakshaykaushik** [comment]
Sorry folks, i gave a thought over supporting this for release pipelines but it will take a lot of effort from my side to support release pipelines as it has a completely different set of APIs. Although, i would be happy if anyone can raise a PR to support it and we can merge it in this code base.  I am adding in documentation that release pipeline is not supported yet.
Keeping this issue open for 15 days, if anyone tumbles across it and wants to contribute.

**Comment by lakshaykaushik** [comment]
Documented as not supported. No immediate future plans
