### ISSUE TITLE
Errors when running publishhtmlreport task

### ISSUE THREAD

**Issue by aurimasroxit97** [lakshaykaushik/PublishHTMLReport#28]
My JMeter CLI command:
jmeter -n -t mytests.jmx -l LoadReports/results.jtl -e -o LoadReports

When I view the results UI locally, everything works fine.

However, when I run _publishhtmlreport_ on a pipeline, I get some errors regarding files that are missing. (See errors.txt attachment). 

I defined the task as follows:
    - task: publishhtmlreport@1
      inputs:
        htmlType: 'Jmeter'
        JmeterReportsPath: '$(Build.SourcesDirectory)/LoadReports'

[errors.txt](https://github.com/lakshaykaushik/PublishHTMLReport/files/5919630/errors.txt)

**Comment by lakshaykaushik** [comment]
Can you paste screenshot of the contents of LoadReports folder after running jmeter tests.

**Comment by aurimasroxit97** [comment]
@lakshaykaushik Sure, there it is.

[drop.zip](https://github.com/lakshaykaushik/PublishHTMLReport/files/5923665/drop.zip)

**Comment by lakshaykaushik** [comment]
Come here to discuss: https://gitter.im/PublishHTMLReports/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by aurimasroxit97** [comment]
@lakshaykaushik You were correct, I found the issue. However, maybe it would be useful to make an improvement to output an error with "specified path can not be located" to the console or something similar, to make it easier to debug? Anyway, thank you :)
