### ISSUE TITLE
report tab never renders report

### ISSUE THREAD

**Issue by mcaljamj** [lakshaykaushik/PublishHTMLReport#30]
I am publishing a genericHTML. The build task completes successfully. On viewing the report tab of the build it never renders the data, instead it just says "PublishHTMLReports is taking longer than expected to load." I have had the task upload different html files all with the same result. Thus I don't think its file content related.

I am using Azure DevOps 2019 system.

I notice in chrome dev tools network activity when going to the report tab that it makes a request to show the index.html page via an IP address that is not our TFS server!

http://10.163.220.3:8086/tfs/_apis/public/gallery/publisher/LakshayKaushik/extension/PublishHTMLReports/1.1.52/assetbyname/index.html

If i replace the bogus IP with the 'real' servername and visit that in a browser then i see a page rendered for Apache JMETER dashboard.

**Comment by lakshaykaushik** [comment]
Can you double check the above IP, looks like a private IP of your box. The extension does not get rendered from any such IP or for that matter any box. It's static content is maintained in vsassets.

**Comment by mcaljamj** [comment]
The IP mentioned does not exist on our on-prem network

**Comment by kshitijcode** [comment]
Hi @mcaljamj , I tried reproducing it on my end and it seems to work fine . [](url)
![Screenshot 2021-02-08 at 3 07 28 PM](https://user-images.githubusercontent.com/15818044/107204544-c9ae2e80-6a22-11eb-979b-72b1652e5e87.png)

I have attached the corresponding  URL route.
It seems you might be using some proxy server like nginx or haproxy .

**Comment by mcaljamj** [comment]
There is no reverse proxy involved.

Today I happened to go to a build from last week which had used the task and the PublishedHTML tab is showing the data! Naturally chrome dev tools is showing the correct server name and not some odd IP address. I cannot explain this. The only thing I know configuration wise that has changed was the install of an additional TFS extension today. I don't see how that could have altered anything. This may be a mystery that will never be solved.
