### ISSUE TITLE
Publishing multiple reports

### ISSUE THREAD

**Issue by PrateekChauhan0194** [lakshaykaushik/PublishHTMLReport#31]
Does this extension have the capability of publishing multiple generic reports at the same time?

**Use case**: There are multiple jobs running the integration tests in an azure pipeline. I want to publish the generated HTML test report in the same pipeline.

Do we have the support for this?

**Comment by lakshaykaushik** [comment]
currently no. If you understand the code base, would be happy to receive a PR which supports this.

**Comment by lakshaykaushik** [comment]
Not supported as of last release
