### ISSUE TITLE
Missing extension License Info on Marketplace

### ISSUE THREAD

**Issue by marriagaTR** [lakshaykaushik/PublishHTMLReport#32]
Private Azure DevOps Org admin replied that 3rd party ADO Marketplace extensions without license are not allowed to be installed.

Example:

- Screenshot:
![image](https://user-images.githubusercontent.com/79720405/109345263-7a933680-7835-11eb-8538-43666ef9d672.png)

- Example Link: https://marketplace.visualstudio.com/items/SonarSource.sonarqube/license

**Comment by marriagaTR** [comment]
Let me know further questions, comments or missing details please @lakshaykaushik

**Comment by marriagaTR** [comment]
As per [Develop extensions/Reference/Manifest reference/Optional attributes/Discovery attributes](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#discovery-attributes), its just a matter of adding the path to the license info as value of "content" array item "license" in [/lakshaykaushik/PublishHTMLReport/vss-extension.json](/lakshaykaushik/PublishHTMLReport/blob/main/vss-extension.json) file:

```
"content": {
        "details": {
            "path": "readme.md"
        },
        "license": {
            "path": "eula.md"
        }
```

**Comment by marriagaTR** [comment]
@lakshaykaushik not sure if extension **".md"** is mandatory as license file name is [LICENSE](https://github.com/lakshaykaushik/PublishHTMLReport/blob/main/LICENSE)

**Comment by lakshaykaushik** [comment]
Merged PR which closes this.
