### ISSUE TITLE
Robotframework log.html results

### ISSUE THREAD

**Issue by JoostW42** [lakshaykaushik/PublishHTMLReport#35]
Hi, In Azure DevOps I have set up a pipeline (CI) with robot tests that are started with a powershell script.

Now I want to integrate these test results (log.html) into a dashboard (passed / failed / history / duration testing).

Is the extension PublishHTMLReports good  enough for using of robot html results in the form of a dashboard?

And is there documentation on how to set up this specifically for robot testing in the pipeline?

Please hear it and thank you for the responses!

**Comment by lakshaykaushik** [comment]
Robot framework is not supported yet.

**Comment by JoostW42** [comment]
Hi, 
thanks for the respons.
When do you expect it to be supported?

That would be nice not only for me, but also for others who use the robot framework

**Comment by lakshaykaushik** [comment]
Can you attach sample Robot framework report with this issue. Will try supporting it

**Comment by JoostW42** [comment]
Hi,
A report on what it can look like, see attached. It is also useful that you can navigate in the report / dashboard to your robot log / report.html

**Attachment:**
Example report.html from report
Example dashboard

![example_dashboard](https://user-images.githubusercontent.com/81220059/113393042-5ed00280-9396-11eb-92c8-8768177f62b2.png)
![example_report_html pptx](https://user-images.githubusercontent.com/81220059/113393044-5f689900-9396-11eb-9fdc-ece12579ad11.png)

**Comment by anhphong1110** [comment]
+1 for enhancement . Robotframework user is large. This plugin is very helpful if it support Robotframework report.

**Comment by JoostW42** [comment]
Hi, What is the status of the modification of the extension "PublishHTMLReport", so that robotframework reports also can be supported?

**Comment by lakshaykaushik** [comment]
Sorry folks, i am short in bandwidth. Cannot support Robot framework in. near future.  Although i am happy if someone else can pick this up and i will be able to merge the PR
