### ISSUE TITLE
Not sure to understand how it displays the report for genericHTML report type

### ISSUE THREAD

**Issue by Bhadja** [lakshaykaushik/PublishHTMLReport#36]
I'm running the publishhtmlreport@1 task in a pipeline to display the result of the database comparison. I'm passing genericHTML to htmlType parameter. This task always runs successfully in the pipeline but it doesn't open the report in a new tab or doesn't provide a URL where the report is published. It is not clear how to use this extension for generic HTML type.

**Comment by lakshaykaushik** [comment]
Where are you using it? Release pipeline? It is not supported in release pipeline. It works only with build pipelines.

**Comment by lakshaykaushik** [comment]
Duplicate issue.
