### ISSUE TITLE
The task "PublishHTMLReport" doen't work in a release pipeline

### ISSUE THREAD

**Issue by yfrindel** [lakshaykaushik/PublishHTMLReport#40]
The task "PublishHTMLReport" is available in a release pipeline, but the report is not published (not visible)

**Comment by gonchalo620** [comment]
Me too

**Comment by DharaniMoorthy** [comment]
Yes, Its not working in release pipeline

**Comment by lakshaykaushik** [comment]
This extension wont work in release pipeline, I have documented that.
There are ways to make it work, but that involves a lot of work, if you can pick it up, ill review the PR and merge it

**Comment by lakshaykaushik** [comment]
this is documented as not supported as of now
