### ISSUE TITLE
Add support for all referenced files (png, jpeg, json etc)

### ISSUE THREAD

**Issue by tusharh2011** [lakshaykaushik/PublishHTMLReport#41]
Could you make sure that I can use not only html files in the report but also all other files within the report directory?

For example, my report has image tags which refers to the PNG and JPEG or JSON files within the same folder. But, if I click on the image links from HTML report within azure, it throws error "doesn't contain the requested asset type 'dist/Screenshots/Calculator.netHome.png' in version" "typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionAssetNotFoundException, Microsoft.VisualStudio.Services.Gallery.WebApi"

**Comment by lakshaykaushik** [comment]
No plans for support of these files in near future. Sorry folks
