### ISSUE TITLE
Can you attach sample Robot framework report with this issue. Will try supporting it

### ISSUE THREAD

**Issue by JoostW42** [lakshaykaushik/PublishHTMLReport#42]
Can you attach sample Robot framework report with this issue. Will try supporting it

_Originally posted by @lakshaykaushik in https://github.com/lakshaykaushik/PublishHTMLReport/issues/35#issuecomment-811826009_

**Comment by JoostW42** [comment]
Hi, 

When is it expected that robot framework will be supported by using the extension PublishHTMLReports?

Greetz,
Joost

**Comment by lakshaykaushik** [comment]
No plans for Robot report support in near future. Sorry folks
