### ISSUE TITLE
The genericHTML is not working

### ISSUE THREAD

**Issue by felipecp** [lakshaykaushik/PublishHTMLReport#48]
The Generic HTML is not working.
The task executed fine but i couldn't see the html page.
The strange thing happened, the jmeter report appear for some seconds and disappear.

    - job: PublishHtmlReportTest
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: publishhtmlreport@1
          inputs:
            htmlType: 'genericHTML'
            htmlPath: '$(Build.SourcesDirectory)/dashboard/charts.html'

**Comment by lakshaykaushik** [comment]
If the html contains js files which are refered in some files and folders, it won't work out of the box. For this to work the extension needs to be modified as per the specific use case(as what i have done for jmeter), steps to do so have been included in the readme.
