### ISSUE TITLE
Custom Graphs over time throws exception

### ISSUE THREAD

**Issue by pabrams** [lakshaykaushik/PublishHTMLReport#9]
When I expand "Custom Graphs"  and select the item in there, I get this:
_{"$id":"1","innerException":null,"message":"The extension 'LakshayKaushik.PublishHTMLReports' doesn't contain the requested asset type 'CustomsGraphs.html' in version '1.1.43'.","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionAssetNotFoundException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionAssetNotFoundException","errorCode":0,"eventId":3000}_

I'm on ADO server 2019, and currently using Edge

**Comment by lakshaykaushik** [comment]
I have fixed this now, do you have some custom graphs to test this ? Let me know if it still fails.

**Comment by pabrams** [comment]
I don't have any custom graphs, but I think I can probably still test your fix and confirm I don't receive the exception?  Will be next week sometime - I don't have permission to update the extension.

**Comment by lakshaykaushik** [comment]
Yes, you wont get exception now. Closing this. Re-Open if you still see the exception.
